### ISSUE TITLE
1.19.3 Version?

### ISSUE THREAD

**Issue by ExiledLizard** [ZaksenCode/Damageful#1]
Hey, @ZaksenCode , can you possibly develop a **1.19.3** version of your mod: "_Damageful_"? Why **1.19.3**? Because that's my main client version. I also find this mod very interesting and useful.

**Comment by ZaksenCode** [comment]
I'll try to post a new version in a few days.

**Comment by ExiledLizard** [comment]
Ok, thanks!

**Comment by ZaksenCode** [comment]
Here is it: https://modrinth.com/mod/damageful/version/wzJltart
