### ISSUE TITLE
Mod Doesn't Display DMG Particles on Servers

### ISSUE THREAD

**Issue by ExiledLizard** [ZaksenCode/Damageful#2]
Hey, @ZaksenCode , thanks for the **1.19.3** version of the _Damageful_ mod! The mod works great, but there is **1** issue: it doesn't display the damage particles, when playing on a **3rd Party Server**. Here's a comparison video of the mod running in a Single-Player world, and on a Server: [You Don't have to Download It](https://www.mediafire.com/file/8qy19mf95uf0qru/Server_-_Singleplayer_Functionality.mov/file)

**Comment by ZaksenCode** [comment]
Hmm, I get the problem, I'll see what I can do.

**Comment by ExiledLizard** [comment]
Also, @ZaksenCode , the mod's damage calculator ignores armor. So if I hit (with my fist) a Husk, that is equipped with full Diamond armor, the particle will still display "1", not a lower number. Also, you could add support for protection, feather falling, and the Resistance pot effect? That's all the feedback I have on your mod.

**Comment by ZaksenCode** [comment]
What do you mean by the feather falling effect support?

**Comment by ExiledLizard** [comment]
Oh, @ZaksenCode , what I meant, is adding _support_ for the **Feather Falling Enchantment**, **Protection Enchantment**, the **Resistance potion effect**, and armor. If the "support" was implemented, the the number particles will display accurate values, based on the entity's armor amount, armor enchants (Like Protection/Feather Falling, E.C.T).

**Comment by ExiledLizard** [comment]
@ZaksenCode, thanks for the updated mod (server support)! But, the game crashed, because of some color out of bounds issue. Here's the crash report: [crash-2024-06-12_16.45.34-client.txt](https://github.com/user-attachments/files/15812022/crash-2024-06-12_16.45.34-client.txt)

**Comment by ZaksenCode** [comment]
It's a little weird. I can reproduce this error. Can you give more details on this? Are you just loading the mod and it starts crashing? try remove the config if you are used a previous version
